# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  shortcut-api:
    build:
      context: shortcut-api
      target: final
    ports:
      - 1192:1192

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: shortcut
      MYSQL_USER: shortcut
      MYSQL_PASSWORD: password
      BIND-ADDRESS: 0.0.0.0
    restart: always
    volumes:
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s

  init-db:
    image: rust:1.73-slim-bookworm
    entrypoint: /entrypoint.sh
    working_dir: /app
    volumes:
      - type: bind
        source: "./migrations/"
        target: "/app/migrations"
      - type: bind
        source: "./shortcut-api/entrypoint.sh"
        target: "/entrypoint.sh"
      - type: bind
        source: "./shortcut-api/src"
        read_only: true
        target: "/app/src"
      - type: bind
        source: "./shortcut-api/Cargo.toml"
        read_only: true
        target: "/app/Cargo.toml"
    environment:
      DATABASE_URL: mysql://shortcut:password@mysql:3306/shortcut
    depends_on:
      mysql:
        condition: service_healthy

  # Test environment
  api-test:
    build:
      context: shortcut-api
      target: build
    command: cargo test
    volumes:
      - type: bind
        source: "./shortcut-api/src"
        target: "/app/src"
      - type: bind
        source: "./shortcut-api/build.rs"
        target: "/app/build.rs"
      - type: bind
        source: "./shortcut-api/Cargo.toml"
        target: "/app/Cargo.toml"
    environment:
      MYSQL_DATABASE: shortcut
      MYSQL_USER: shortcut
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    profiles:
      - test
    depends_on:
      init-db:
        condition: service_completed_successfully

