# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  api:
    build:
      context: .
      dockerfile: shortcut-api/Dockerfile
      target: final
    command: /bin/server --database-url postgres://shortcut:password@db:5432/shortcut --bind-address 0.0.0.0
    restart: always
    ports:
      - 127.0.0.1:1192:1192
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    user: postgres
    restart: always
    environment:
      POSTGRES_USER: shortcut
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortcut
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wait-for-init-db:
    image: bash:5.2
    command: echo hello
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: {}
