name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
      SQLX_OFFLINE: true
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
    - name: Install protoc
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler libprotobuf-dev clang-format

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check code
      run: cargo check

    - name: Check code with Clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings

    - name: Lint protobuf
      run: clang-format --dry-run --Werror proto/*.proto

  small-test:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
      SQLX_OFFLINE: true
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Install protoc
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Running small tests
      run: cargo test --all-features --bins --lib

  midium-test:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
      DATABASE_URL: postgres://shortcut:password@localhost:5432/shortcut
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable

    - name: Install protoc
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler libprotobuf-dev

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: docker/setup-buildx-action@v2

    - uses: docker/build-push-action@v4
      with:
        load: true
        context: .
        file: shortcut-api/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Pull images
      run: docker compose pull

    - name: Build
      run: docker compose build

    - name: Run API and DB
      run: docker compose up -d

    - name: DB migration
      run: |
        cargo install sqlx-cli --no-default-features --features rustls,postgres
        cargo sqlx migrate run

    - name: Run medium tests
      run: cargo test --tests
